#!/bin/bash
ip=$1
PORT=$2
PROTO=$3
if [[ $3 == "tcp" ]]; then scan=sT; fi
if [[ $3 == "udp" ]]; then scan=sU; fi
if [[ $(sudo nmap -$scan -p$2 $ip --min-rate 5000 | grep open) ]]; then echo "1" ; else echo "0"; fi


